# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: David H Zhan
title: Biomedical Researcher
#email: <to_add>
website: https://david-h-zhan.github.io/resume/

# Dark Mode (true/false/never)
darkmode: true

# Social links
#twitter_username: facespics
#github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: david-huiwang-zhan-383ba23a
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: My resume
  icon: fas fa-globe
  url: https://david-h-zhan.github.io/resume/
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a postdoctoral researcher at _Johns Hopkins University, School of Medicine_. Over the past 13+ years, I have
  accumulated extensive research experience in cancer, immunology, neuroscience and drug discovery, as well as
  experience in a wide range of cutting-edge biotechnologies and computational methods.
  My research articles have been published in high-impact journals such as _Developmental Cell_, _Science Advances_
  and _PNAS_, in addition to being invited for oral presentations at many international conferences, a comprehensive
  list of which can be found towards the bottom of this page.

  In my spare time, I have participated in many extracurricular activities that have helped me develop my soft skills
  and gather commercial experiences. Examples include leading a team in student consulting case competitions and
  undertaking short-term projects at consulting and investment firms such as _McKinsey_ and _T. Rowe Price_ -- again
  a long list of these can be found below.

content:
  - title: Academic Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top # (options: left, right, top, top-right, top-middle)
        title: Johns Hopkins University, School of Medicine
        caption: 2020 - present
        sub_title: Postdoctoral Fellow, Peter Devreotes Lab
        #        quote: >
        #          Some quote*
        description: | # this will include new lines to allow paragraphs
          Mentor: Peter Devreotes _(Member of the National Academy of Sciences, Department Chair at JHU-SOM)_

          My Post-doctoral research focuses on energy regulation of cancer cells. Tumors are inclined to metabolize
          glucose anaerobically through glycolysis with lower ATP production efficiency rather than aerobically
          even when oxygen is available. This was reported by Otto Warburg 100 years ago, yet the mechanism
          hitherto is not well-understood. My new findings have led us to propose a completely novel mechanism
          that glycolysis can be enriched and accelerated in cell cortex instead of only taking place in the cytosol
          as traditionally viewed, and this provides an exciting explanation on the Warburg effect in cancer cells.
          We are currently preparing the manuscript for publication and we believe this is a potentially
          paradigm-shifting research, and will have far-reaching implications for understanding and treating cancer.

      - layout: top
        title: Johns Hopkins University, School of Medicine
        caption: 2012 - 2020
        sub_title: Doctor of Philosophy (Ph.D.), Biological Chemistry
#        quote: >
#          Some quote*
        description: | # this will include new lines to allow paragraphs
          Mentors:
          - 2014 - 2020: Peter Devreotes & Chuan-Hsiang (Bear) Huang
          - 2012 - 2014: Gregg Semenza

          My main PhD work found that the excitable signaling and cytoskeletal network components controlling cell
          migration and oncogenic transformation propagate as cortical waves, and this work led to a completely
          novel view of cancer progression as a shift to a lower threshold of these excitable networks.
          With the help of computational simulations, this work provided a systems-level understanding of the intrinsic
          property of these networks and raised up threshold as the new potential target for cancer assessment
          and intervention. The manuscript was published in <mark>Developmental Cell</mark> and featured as the
          [cover article](https://www.cell.com/developmental-cell/issue?pii=S1534-5807(19)X0018-0#Articles).

          Other research projects:
          - 2013.04 - 2013.12, _Oxygen Regulation in Cancer and Organ Transplantation_ \\
          Mentor: Gregg Semenza (Nobel Prize Laureate, Member of the National Academy of Sciences & National Academy of Medicine, JHU-SOM)\\
          Studied the crosstalk of WNT pathway and HIF-1 pathway in Cancer Stem Cell progression, and the role of HIF-1 in Epithelial to Mesenchymal Transition of cancer cells and in Remote Ischemic Preconditioning of the heart.

          - 2012.12 - 2013.03, _Neuronal Synapse and Memory Formation_ \\
          Mentor: Richard Huganir (Member of the National Academy of Sciences, HHMI, Department Chair at JHU-SOM)\\
          Studied the interaction of neuronal transmitter receptor AMPR and protein SRPX2 in rat neuron.

          - 2012.09 - 2012.11, _Heal the Wound with Keratin_ \\
          Mentor: Pierre Coulombe (Department Chair at JHU-SPH)\\
          Studied the function of keratins K6, K16 and K17 during the wound healing process of mouse skin.

          - Side projects:
            - Epithelial to Mesenchymal Transition in human mammary gland cells and _iPS cells_
            - Collaboration with Liu Jun Lab at JHU: the mechanism of a newly synthesized small molecule (WL5A5) as a _novel potential drug for breast cancer_
            - _Air Force Office of Scientific Research_ - Multidisciplinary Research Program of the University Research Initiative project: how the excitability of Ras/PI3K/ERK-Actin network regulates the migration of cancer cells in electric field

      - layout: top
        title: Xiamen University, China
        caption: 2008 - 2012
        sub_title: Bachelor of Science (B.S.), Biological Sciences
#        quote: >
#          GPA: 3.92/4*
        description: | # this will include new lines to allow paragraphs
          _GPA: 3.92/4_

          Exchange experiences:
          - 2011.07 - 2012.04: Peking University, China
          - 2011.02 - 2011.06 National Tsing Hua University, Taiwan

          Research projects:
          - 2011.07 - 2012.04, _Homosexual Behavior and Sex Sensation in Mice_, Yi Rao Lab, Peking University\\
          Studied how neuronal transmitter 5-HT influence the intersexual and homosexual odor sensation and courtship behavior in mice.

          - 2011.02 - 2011.06, _Regulation of Gene Expression_, Lih-Yuan Lin Lab, National Tsing Hua University\\
          Investigated the binding of PTEN and C/EBP alpha to the promoter region of Metallothionein gene.

          - 2010.06 - 2010.12, _Signaling of Cell Death_, Jia-Huai Han Lab, State Key Lab of Cellular Stress Biology, Xiamen University\\
          Studied the regulation of apoptosis by the complex of Vacuole Membrane Protein 1 and V-ATPase.

          - 2009.06 - 2010.05, _Cancer Drug Screen_, Qing-Xi Chen Lab, State Key Lab of Cellular Stress Biology, Xiamen University\\
          Investigated how a novel anti-cancer drug (ESC-3) induces apoptosis of human bile duct carcinoma cells.

#  - title: Projects # Title for the section
#    layout: list # Type of content section (list/text)
#    content:
#      - layout: top-middle
#        title: Super awesome project
#        link: github.com/sproogen
#        # link_text: Project Website
#        additional_links:
#          - title: sproogen/modern-resume-theme
#            icon: fab fa-github
#            url: github.com/sproogen/modern-resume-theme
#          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
#          #   icon: fab fa-github
#          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
#        quote: >
#          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
#        description: | # this will include new lines to allow paragraphs
#          Some description about the project

  - title: Work Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top
        title: McKinsey & Company
#        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Externship, Part-time Literature Reviewer for Innovative Cancer Treatment Project.
        caption: 2018.07 - 2018.08
#        quote: >
#          Some quote*
#        description: | # this will include new lines to allow paragraphs

      - layout: top
        title: McKinsey & Company
        sub_title: Externship, Part-time Literature Reviewer for Immunological Drug Project.
        caption: 2018.01 - 2018.02
#        description: | # this will include new lines to allow paragraphs

      - layout: top
        title: T. Rowe Price Investment Management Company
        sub_title: Externship, Research Analyst
        caption: 2017.07 - 2017.09
        description: | # this will include new lines to allow paragraphs
          Completed a research project studying the Biotech & Pharmaceutical stocks.

      - layout: top
        title: Flag-Smart Venture Capital Inc.
        sub_title: Externship, Part-time Consultant in Biotechnology Division
        caption: 2016.10 - 2017.05
        description: | # this will include new lines to allow paragraphs
          Analyzed and evaluated 3 biotechnology start-up projects.

      - layout: top
        title: Johns Hopkins Graduate Consulting Club
        sub_title: Consultant (Pro Bono Consulting Project)
        caption: 2016.10 - 2017.02
        description: | # this will include new lines to allow paragraphs
          Helped a non-governmental organization, Ashoka, analyze the flaws in the current US patent system
          and provided two innovative proposals to the client.

      - layout: top
        title: BrainFrame Inc. (start-up project under Johns Hopkins Medical Entrepreneurship Program)
        sub_title: Chief Science Officer
        caption: 2016.10 - 2016.12
        description: | # this will include new lines to allow paragraphs
          Focused on developing a frame to culture Mini-brain Organoid.

      - layout: top
        title: Sino-American Pharmaceutical Professionals Association
        sub_title: Board Member, JHU Representative
        caption: 2017.08 - 2019.08

      - layout: top
        title: Hopkins Biotech Network, JHU
        sub_title: Executive Board Member, Co-director for Alumni Relationship
        caption: 2016.08 - 2019.07

      - layout: top
        title: Graduate Student Association, JHU
        sub_title: Executive Board Member, Representative of BC Program
        caption: 2016.08 - 2019.07

  - title: Other Experience # Title for the section
    layout: text # Type of content section (list/text)
    content: |
      - Team Leader, Biotech & Healthcare Consulting Case Competition (Johns Hopkins Graduate Consulting Club) _(2017.04)_
      - Team Leader, Consulting Case Competition (Johns Hopkins Graduate Consulting Club) _(2016.11)_
      - Program Facilitator for the National Youth Leadership Forum (NYLF) in Medicine (Washington DC Session) _(2014.06)_

      - Organizer & Host of Lewis Talks (Serial Academic Seminars of Cell Biology Department in Johns Hopkins University School of Medicine) _(2022.01-2022.06)_
      - Teaching Assistant for Cell Physiology Course for Medical Student (Johns Hopkins University) _(2015 - 2019)_
      - Studied courses in Drug Discovery & Business: _Introduction to Drug Discovery Research, Drug Discovery Case Studies, Pharmaceutical Enterprise, Medical Entrepreneurship, Fundamental Accounting, Fundamental Financing_ _(2016 - 2018)_

  - title: Publications # Title for the section
    layout: text # Type of content section (list/text)
    content: | # this will include new lines to allow paragraphs
      Articles:
      - **Zhan, H.**, Huang, C.H. and Devreotes, P.N., 2022. Glycolysis is enriched as propagating waves in cell cortex as a new mechanism for cancer cell progression. _(In Preparation)_
      - **Zhan, H.**, Bhattacharya, S., Cai, H., Iglesias, P.A., Huang, C.H. and Devreotes, P.N., 2020. An excitable Ras/PI3K/ERK signaling network controls migration and oncogenic transformation in epithelial cells. <mark>Developmental Cell</mark>, 54(5), pp.608-623. _(Selected for [Cover Story](https://www.cell.com/developmental-cell/issue?pii=S1534-5807(19)X0018-0#Articles))_
      - Bhattacharya, S., Banerjee, T., Miao, Y., **Zhan, H.**, Devreotes, P.N. and Iglesias, P.A., 2020. Traveling and standing waves mediate pattern formation in cellular protrusions. <mark>Science Advances</mark>, 6(32), p.eaay7682.
      - Neumann, N.M., Perrone, M.C., Veldhuis, J.H., Huebner, R.J., **Zhan, H.**, Devreotes, P.N., Brodland, G.W. and Ewald, A.J., 2018. Coordination of receptor tyrosine kinase signaling and interfacial tension dynamics drives radial intercalation and tube elongation. <mark>Developmental Cell</mark>, 45(1), pp.67-82.
      - Cai, Z., Luo, W., **Zhan, H.** and Semenza, G.L., 2013. Hypoxia-inducible factor 1 is required for remote ischemic preconditioning of the heart. <mark>Proceedings of the National Academy of Sciences</mark>, 110(43), pp.17462-17467.
      - Song, W., Shen, D.Y., Kang, J.H., Li, S.S., **Zhan, H.**W., Shi, Y., Xiong, Y.X., Liang, G. and Chen, Q.X., 2012. Apoptosis of human cholangiocarcinoma cells induced by ESC-3 from Crocodylus siamensis bile. <mark>World Journal of Gastroenterology: WJG</mark>, 18(7), p.704.

      Oral Presentations:
      - 2021 Cold Spring Harbor Laboratory Meeting: Cellular Dynamics & Models _(2021.05.19)_
      - 2020 American Society for Cell Biology Annual Meeting: Subgroup “How Oncogenes Rewire the Cell” _(2020.12.08)_
      - American Society for Biochemistry and Molecular Biology Lipid Research Division Seminar Series: New Roles for Phosphoinositides in Membrane Signaling _(2020.11.11)_
      - The Joint PI3K Online Seminar Series of UCL (University College London) and MSKCC (Memorial Sloan Kettering Cancer Center) _(2020.10.09)_
      - Johns Hopkins School of Medicine Center for Cell Dynamics Seminar Series _(2019.10.25)_
      - 2019 Air Force Office of Scientific Research Biophysics Multidisciplinary University Research Initiatives (MURI) Program Review Meeting _(2019.05.08)_
      - Johns Hopkins University School of Medicine Department of Biological Chemistry Annual Retreat _(2018.10.10)_
      - 2017 Air Force Office of Scientific Research Biophysics Multidisciplinary University Research Initiatives (MURI) Program Review Meeting _(2017.10.11)_

      Poster Presentations:
      - 2020 American Society for Cell Biology Annual Meeting _(2020.12)_
      - 2019 American Society for Cell Biology Annual Meeting _(2019.12)_
      - 2019 Biophysical Society Annual Meeting _(2019.03)_
      - 2019 Gordon Research Conference: Directed Cell Migration _(2019.01)_
      - 2017 American Society for Cell Biology Annual Meeting _(2017.12)_
      - 2017 American Association for Cancer Research Annual Meeting _(2017.04)_
      - 2015 Biophysical Society Annual Meeting _(2015.02)_

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in biomedical research, some of my other interests and hobbies are:
      - Hobby 1
      - Hobby 2
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/resume/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: False
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
